guild_id bigint NOT NULL DEFAULT 000000000000000000,
default_log_webhook text,
is_premium boolean NOT NULL DEFAULT False,
required_age smallint NOT NULL DEFAULT 7,
raidmode_log text,
raidmode_status boolean NOT NULL DEFAULT False,
role_log text,
message_log text,
channel_log text,
guild_log text,
voice_log text,
member_log text,
is_member_logs boolean NOT NULL DEFAULT False,
join_leave_logs text,
bot_role bigint,
assign_bot_role boolean NOT NULL DEFAULT False,
greet_member boolean NOT NULL DEFAULT False,
greeting_channel bigint,
greetings text[],
greet_bot bigint,
goodbyes text[],
depart_channel bigint,
farewell_member boolean,
fatrewell_bot boolean,